### ISSUE TITLE
64-bit version

### ISSUE THREAD

**Issue by peter-frentrup** [peter-frentrup/NppMenuSearch#1]
Sourceforge user *eavisomark* requested [sf-feature-request #5](https://sourceforge.net/p/nppmenusearch/feature-requests/5/):

Please provide a 64-bit version for 64-bit notepad++.

**Comment by benyaminl** [comment]
Yes we're waiting for it

**Comment by rekna1** [comment]
Apparently our company has pushed 64bits version of notepad++ due to security reasons, so please provide a 64bits version of your plugin!!!

**Comment by benyaminl** [comment]
@rekna1 Please no exclamation mark please.. Because it seems intimidating. Thanks
