### ISSUE TITLE
Failure to load in machine with .net 4.5

### ISSUE THREAD

**Issue by computHome** [peter-frentrup/NppMenuSearch#11]
My office machine Win10 only has .net 4.5 and it failed to load and it asked me to install .net 3.5 or lower, is there any way to load it with 4.5 since the machine couldn't install older version of software?

**Comment by peter-frentrup** [comment]
Apart from recompiling it yourself with a .Net 4.5 toolchain, no. 
I do not want to maintain multiple binaries for different .Net platforms. 

Maybe, I will rewrite the whole plugin in native C++ to get rid of the .Net dependency. But this plan exists for several years already and it will likely remain a plan/wish for quite some time.

**Comment by bahusoid** [comment]
@computHome  Actually you might try to add the following unzipped file near notepad++.exe. In theory it should force app to use .NET 4
[notepad++.exe.config.zip](https://github.com/peter-frentrup/NppMenuSearch/files/1380483/notepad.exe.config.zip)

**Comment by computHome** [comment]
@behusoid Thanks, it works!
