### ISSUE TITLE
Notepad 7.5.4 this plugin is not working

### ISSUE THREAD

**Issue by av930** [peter-frentrup/NppMenuSearch#14]
please find the issue.
I really want to use this plugin. 
Thanks in advance.

**Comment by chcg** [comment]
@av930 Which version of the plugin are you using? 32bit\64bit and on which windows?

**Comment by rekna1** [comment]
Same here : 64bit plugin error: Failed to load, NppMenuSearch is not compatible with the current version of Notepad++ (windows10, notepad++ 64bit 7.5.4)

**Comment by rekna1** [comment]
Any update on this issue ?

**Comment by budul100** [comment]
Major problem is an update needed to the current version of NPPPluginNetHelper.cs. I've made a [respective pull request](https://github.com/peter-frentrup/NppMenuSearch/pull/16).

**Comment by untergrundbiber** [comment]
When will the new binaries be available?

**Comment by chcg** [comment]
@untergrundbiber You might want to checkout CI build from https://ci.appveyor.com/project/chcg/nppmenusearch/builds/22995219/job/wawyy9ncrgegjjwq/artifacts, based on current master and PR #12

**Comment by untergrundbiber** [comment]
Many thanks, works like a charm  :)
