### ISSUE TITLE
notepad++.exe process still remaining open after closing

### ISSUE THREAD

**Issue by Diz-57** [peter-frentrup/NppMenuSearch#15]
like the issue with dspellcheck.dll, but the conflicts are with jn.dll and nppexec.dll.  removing both of these or nppmenusearch.dll fixes it.  the issue doesnt happen with nppmenusearch version 0.8 and older.

**Comment by dinkumoil** [comment]
As I already reported [here](https://sourceforge.net/p/nppmenusearch/bugs/12/) I was able to overcome this problem by installing the _NppFTP_ plugin. I guess it it caused by some sort of timing problem or a race condition when Notepad++ terminates.

**Comment by Diz-57** [comment]
I wrote that so long ago id forgotten about it! Thanks, but the issue is gone for me now anyway.
