### ISSUE TITLE
reference this plugin in the official plugin list

### ISSUE THREAD

**Issue by cmeriaux** [peter-frentrup/NppMenuSearch#18]
Could you please add your nice plugin to the official NppPluginList repository ?
See:   
- https://github.com/notepad-plus-plus/nppPluginList 
- https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x86.json 

Thanks

**Comment by peter-frentrup** [comment]
Dear @cmeriaux,
I just released version 0.9.5 and created a pull-request https://github.com/notepad-plus-plus/nppPluginList/pull/358 to update the official plugin list.
Peter
