### ISSUE TITLE
[Bug] Incompatibility with Explorer plugin

### ISSUE THREAD

**Issue by pidgeon777** [peter-frentrup/NppMenuSearch#19]
NppMenuSearch appears not to be compatible with Explorer plugin, as I also mentioned to Explorer author:

https://github.com/funap/npp-explorer-plugin/issues/4

The problem is that Explorer's favorites (some kind of bookmarks) are usually stored in a file called Favorites.dat which always get saved when Notepad++ exits. But if NppMenuSearch is also enabled, then the content of Favorites.dat file gets erased at Notepad++ exit. Disabling NppMenuSearch makes this unwanted behaviour disappear. Thus, an incompatibility between the two plugins actually does exist.

Hopefully, this annoying bug will get a chance to be fixed! I'm willing to help as a beta tester, of course.

**Comment by funap** [comment]
I am terribly sorry to cause you inconvenience.
This issue is due to the Explorer.dll termination process.
please close this issue.

**Comment by trdm** [comment]
Still not fixed? I wrote about this a few months ago.

**Comment by pidgeon777** [comment]
I no longer noticed this bug in my setup since updating both NppMenuSearch and the Explorer plugin to their latest versions.

**Comment by peter-frentrup** [comment]
I guess it is fixed by the new Explorer plugin version.

**Comment by trdm** [comment]
Да ну нафиг, плагин бъет дат-файл другого плагина и вопрос закрыт потому что другой плагин исправил ситуацию.
что тут неправильно.
