### ISSUE TITLE
Search Toolbar is too small on npp restart

### ISSUE THREAD

**Issue by peter-frentrup** [peter-frentrup/NppMenuSearch#2]
@bahusoid reported [sf-bug #10](https://sourceforge.net/p/nppmenusearch/bugs/10/):

> With latest notepad++ version (7.3.3) search toolbar is too small and needs to be adjusted on each npp restart.
>
> I also created issue for notepad++ and it contains more details: [notepad-plus-plus issue #3094](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3094)
>
> This issue appeared starting from 6.7 version where solution was migrated to VS 2013. I didn't find any other changes that could affect this behavior. So maybe it's bug in plugin that doesn't add correctly toolbar and problem is manifested itself only if build is made on latest SDK.

**Comment by bahusoid** [comment]
@peter-frentrup Thanks but your fix isn't working for me (
In fact 0.9.1 doesn't work at all for me - I see no suggestions on any input:
![searchnosuggestions](https://cloud.githubusercontent.com/assets/22025304/25087885/d156f6fa-237a-11e7-9047-62a034e50e57.png)

And regarding this particular problem. I see strange behavior which wasn't there before. 
1) I started Notepad++ with new plugin. I still see small search toolbar:
![newversionsmallsearchtoolbar](https://cloud.githubusercontent.com/assets/22025304/25088061/2a6ed1f8-237c-11e7-927f-99b2bf5d19cc.png)

2) I increased size of Search toolbar to overlap Npp toolbar icons:
![searchtoolbarresizedtooverlapnpptoolbar](https://cloud.githubusercontent.com/assets/22025304/25088074/401f1ea4-237c-11e7-9dec-bb9c5c36c9a9.png)

3) Then I restarted Npp.  Search toolbar is bigger than initially but still placed long after last icon from npp toolbar:
![npprestartedaftertoolbarresized](https://cloud.githubusercontent.com/assets/22025304/25088185/ffc7553c-237c-11e7-876c-939720f0bb76.png)

4) On next Npp restart Search tool bar again small as on first start:
![newversionsmallsearchtoolbar](https://cloud.githubusercontent.com/assets/22025304/25088061/2a6ed1f8-237c-11e7-927f-99b2bf5d19cc.png)

Don't know if it's related but I have Windows taskbar placed on the right:
![fullscreen](https://cloud.githubusercontent.com/assets/22025304/25088284/d1b64d78-237d-11e7-9050-9966cc4f9f17.png)


### Debug Info
Notepad++ v7.3.3   (32-bit)
Build time : Mar 20 2017 - 18:02:01
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll CutNCopyLine.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppMenuSearch.dll NppSaveAsAdmin.dll NppTextFX.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll XMLTools.dll
