### ISSUE TITLE
Can't download binary version 0.9.3 from sourceforge

### ISSUE THREAD

**Issue by brgrvrm** [peter-frentrup/NppMenuSearch#20]
Download the binaries from https://sourceforge.net/projects/nppmenusearch/files/v0.9.3/ doesn't work.

Always get the popup message:

> "The "/v0.9.3/NppMenuSearc..earch_v0.9.3_x64.zip" file could not be found or is not available. Please select another file."

> "The "/v0.9.3/NppMenuSearc..earch_v0.9.3_x86.zip" file could not be found or is not available. Please select another file."

**Comment by peter-frentrup** [comment]
That was indeed strange. It should hopefully work now.

**Comment by brgrvrm** [comment]
It works! (Downloading and also closing NPP)
Many thanks.
