### ISSUE TITLE
Conflict with Customize Toolbar Plugin

### ISSUE THREAD

**Issue by Burzio** [peter-frentrup/NppMenuSearch#21]
Hi,
I have the following issues  installing both Menu Search and Customize Toolbar :
1. Notepad++ remains loaded in memory after Notepad++ close.
2. For each next launch N++ creates another instance in memory and the repeats previous issue
3. Each instance creates a lock on N++ folder.
4. Next attempts of update/uninstall of plugins or N++ fails.

It happens on N++ v7.8.x x64, both N++ sigle/multiple instance option set.
I didn't tried other version or config (I take a lot of time to find the relation between the 2 plugins and I can't continue other test). I'll notice issue to "Customize Toolbar" developer too.

**Comment by Burzio** [comment]
The bug is still present with many other plugins. Customize toolbar is one of many other plugins can be involved by Menu Search plugins. The issue desappears removing it and leving all others.

**Comment by peter-frentrup** [comment]
Dear @Burzio, 
thank you for your report. Which version of NppMenuSearch do you have installed? This issue sounds like #13 and should be fixed in 0.9.3.

Best regards,
Peter

**Comment by Burzio** [comment]
@peter-frentrup,
for N++ 7.8.x x64 the version available to install is 0.9.2 . That explains all. However, it's no clear why  plugins manager doesn't provide last version.

Regards
Burzio

**Comment by dalbocha** [comment]
I had this issue with prior versions of plugin. The latest version (0.9.3.43073) does not collide with CustomizeToolbarPlugin.
