### ISSUE TITLE
Update default text of the search textbox

### ISSUE THREAD

**Issue by dalbocha** [peter-frentrup/NppMenuSearch#22]
Thank you for great plugin. I use it a lot.
While the search box has no focus it shows text "Search Menu & Properties (Ctrl+M)". I changed default key binding for Search Menu to another shortcut. That is why this text for me not relevant, I use another shortcut.
Please remove default shortcut from tip or use assigned one.

**Comment by peter-frentrup** [comment]
Hello,
thank you for your report! I fixed this in commit db84f57.
