### ISSUE TITLE
The search results window doesn't remember its size

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [peter-frentrup/NppMenuSearch#23]
I see that search results window is resizable (by dragging edges or corners). But the new size is not saved and the default value is used when NPP is restarted. Size of this window can be saved in config file.

**Comment by bahusoid** [comment]
I think it's the same issue as mine https://github.com/peter-frentrup/NppMenuSearch/issues/8

In short: Size is saved correctly if not maximized window is used (author's use case). When window is maximized it's not saved correctly. 

You can try using my mod https://github.com/bahusoid/NppMenuSearch/releases/tag/v0.9.2-mod (it actually doesn't save last used size but simply fills all available space instead)

**Comment by peter-frentrup** [comment]
Dear @ArkadiuszMichalski,
thank you for this suggestion. I implemented it in version 0.9.5.
Peter
