### ISSUE TITLE
Scaling issue when 4k screen present

### ISSUE THREAD

**Issue by milichev** [peter-frentrup/NppMenuSearch#24]
On my laptop equipped with a **4k display**, the NppMenuSearch popup menu has a scaling issue (see the picture).

When I open npp on an ordinary HD display with no scaling connected via HDMI the issue persists.

![NppMenuSearch_4k_scaling_bug](https://user-images.githubusercontent.com/533183/74464999-3f79cb80-4e9d-11ea-84f0-b7d08b460136.png)

**Comment by hoangitk** [comment]
Hi @milichev,

You can fix as below pic. I apply ok on my Sureface Pro 6.

![image](https://user-images.githubusercontent.com/342078/86505859-d9fa8d00-bdf3-11ea-9e30-58cdf4db2e89.png)

**Comment by peter-frentrup** [comment]
The issue should be fixed with version 0.9.5
