### ISSUE TITLE
Access Violation on 7.8.3 64-bit with Toolbar "hide"

### ISSUE THREAD

**Issue by vinsworldcom** [peter-frentrup/NppMenuSearch#25]
With N++ 7.8.3 64-bit, NppMenuSearch 0.9.2 and Settings->Preferences...->General->Toolbar "Hide" checked (meaning no toolbar is shown) everything works fine.  When I press the shortcut for NppMenuSearch "Menu Search" (which I mapped to Ctrl-Shift->P) it puts the search box at the top right of my N++ window aligned with the document tab bar.

WIth the same setup as above, except now using the latest version of NppMenuSearch 0.9.3, I get "Access Violation".  When I show the toolbar (uncheck Settings->Preferences...->General->Toolbar "Hide") everything works as expected since the search window is already in the toolbar.

Please bring back the functionality to use this great plugin *with* the toolbar *hide on*.

Notepad++ v7.8.3   (64-bit)
Build time : Jan 12 2020 - 19:09:49
Path : C:\usr\bin\npp64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1686
Plugins : AutoSave.dll BetterMultiSelection.dll ChangedLines.dll CodeAlignmentNpp.dll ColumnTools.dll ComparePlugin.dll CsvQuery.dll DoxyIt.dll DSpellCheck.dll Explorer.dll GitSCM.dll HexEditor.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll NppConsole.dll nppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppMenuSearch.dll PluginManager.dll PreviewHTML.dll Python Indent.dll QuickText.dll SpeechPlugin.dll SurroundSelection.dll TagLEET.dll TagsView.dll XMLTools.dll ZoomDisabler.dll 

Cheers.

**Comment by peter-frentrup** [comment]
Thank you for your investigation and the fix.
