### ISSUE TITLE
displayed icons are mirrored vertically and merged with normal icons

### ISSUE THREAD

**Issue by artie-finkelstein** [peter-frentrup/NppMenuSearch#29]
this is new to 0.95, but also requires MenuIcons 1.230 to be active, it does not show up in NppMenuSearch 0.93 when MenuIcons 1.230 is active.
```
Notepad++ v8.1.4   (32-bit)
Build time : Aug 21 2021 - 12:58:42
Path : C:\Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : MenuIcons.dll NppMenuSearch.dll 
```
this first image is NppMenuSearch 0.93 & MenuIcons 1.230:
![mas desktop 2021 09 05_142900](https://user-images.githubusercontent.com/28426654/132139289-8f36d665-f08a-4296-aa8b-5b1705d75bde.jpg)

this second image is NppMenuSearch 0.95 & MenuIcons 1.230 set to 'Plain text match' (my normal operational mode):
![mas desktop 2021 09 05_143126](https://user-images.githubusercontent.com/28426654/132139294-abc960b4-cae0-47f0-8fab-7df4875af5f3.jpg)

this third image is NppMenuSearch 0.95 & MenuIcons 1.230 set to 'Command ID match':
![mas desktop 2021 09 05_144434](https://user-images.githubusercontent.com/28426654/132139602-60f3cd3a-959f-45df-97d8-2b74bcf3d80a.jpg)
I chose 'Command ID match' as a fast way to stop MenuIcons "providing" the icons but otherwise stay as active as possible.  To me the oddity is that NppMenuSearch not only still shows the icon for [ Language > Define your language... ], but now it shows it correctly.

Note:  These display errors are cosmetic and do not seem to affect the rest of NppMenuSearch functionality.

**Comment by peter-frentrup** [comment]
Dear @artie-finkelstein,

thank you for your report. I can conform the issue and I am working on a fix. The "oddity" with _Define your language..._ in the last screenshot is expected behaviour: when no icon is found in the menu, the toolbar icon is used.

Peter
