### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by Korb** [peter-frentrup/NppMenuSearch#35]
> Cannot load 32-bit plugin.
> NppMenuSearch.dll is not compatible with the current version of Notepad+ + .
> Do you want to remove this plugin from the plugins directory to prevent this message from the next launch?

Please make a 64-bit version.

**Comment by vinsworldcom** [comment]
There is a 64-bit version.  I'm using it.  Install through Plugin Admin or manually from https://sourceforge.net/projects/nppmenusearch/files/v0.9.6/

Cheers.
