### ISSUE TITLE
Switch between code search and menu search

### ISSUE THREAD

**Issue by AG2023** [peter-frentrup/NppMenuSearch#42]
Perhaps it should be called optimization rather than an issue.

Can you add a switch button on the right side of your Menu Search Box，to allow users to choose whether to search for code sheets or search for menu。Since in most cases, user search code sheets are just simply searching for a keyword, but the built-in pop-up search box is really annoying, so we need a quick search box embedded in NPP view (not a float window).

Thanks!

**Comment by peter-frentrup** [comment]
Notepad++ already has a "docked search bar" for the current document: it is available via Search -> Incremental Search (Ctrl+Alt+I).
I will not duplicate that functionality.
